# 5.2 Numpy

***

```{admonition} Advertencia
:class: warning
Este libro está actualmente en proceso de desarrollo, por lo que es posible que algunos de sus contenidos aún no estén disponibles. Agradecemos su comprensión mientras trabajamos en completarlo y mejorar su contenido.
```

`Numpy` es considerada la primera biblioteca que se creó externa a Pyhton con el fin de poder trabajar en computación científica. Su nombre proviene de _"Numerical Python"_.

Es una libreria para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junyo con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

Tiene muchas funciones que permiten hacer cálculos para álgebra lineal, estadística o métodos numéricos que serán de mucha ayuda.

Como `Numpy` es una biblioteca, se tendrá que exportar para poder utilizarla en el código que se esté creando.

***
## Importar biblioteca

Para importar la biblioteca se utiliza `import` y después el nombre de la biblioteca a importar. Además de agregar la _keyword_ `as` para crear un alias a la biblioteca importada.

In [3]:
import numpy as np

La sintaxis es:

```python

    import nombre_biblioteca as alias_biblioteca

```

Se utiliza de forma estándar el alias _np_ para Numpy. Incluso cuando se lea el código de alguien más, es muy común encontrar este reenombre. Esto servirá para que la codificación sea más práctica, rápida y fácil de leer.

Cada vez que se comience un código nuevo, se tendrá que realizar el importe de la biblioteca.

***
## Comandos

Se tiene dos vectores $\vec{u}$ y $\vec{v}$ y se quiere realizar su suma.

$$\begin{matrix}
\vec{u} = \begin{pmatrix}
1\\ 
2\\ 
3
\end{pmatrix} & \vec{v} = \begin{pmatrix}
4\\ 
5\\ 
6
\end{pmatrix} &  \overrightarrow{u+v} = \begin{pmatrix}
5\\ 
7\\ 
9
\end{pmatrix}
\end{matrix}$$

Si se usaran listas : 

In [6]:
u = [1,2,3]
v = [4,5,6]

print(u+v)

[1, 2, 3, 4, 5, 6]


Por lo que no realiza la suma de componente a componente como le corresponde a la suma de vectores. 

Para crear un arreglo se utilizará la función `np.array()`. Dentro de este arreglo irá la lista que contiene los elementos de cada vector. Con esto, ya se pueden tratar como vectores y realizar la suma.

La sintaxis es:

```python
    arreglo = np.array(nombre_lista)
```

In [8]:
x = np.array(u)
y = np.array(v)

print(x+y)

[5 7 9]


Se tienen dos matrices $A$ y $B$ y se quiere realizar su suma.

$$
A = \begin{pmatrix}
1 & 2\\ 
3 &4 
\end{pmatrix}$$


$$
B = \begin{pmatrix}
5 & 6\\ 
7 & 8 
\end{pmatrix}
$$

$$
A+B = \begin{pmatrix}
6 & 8\\ 
10 & 12 
\end{pmatrix}
$$

Si se recuerda, para crear matrices con listas se creaban una dentro de otra. 

In [11]:
A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

print(A+B)

[[1, 2], [3, 4], [5, 6], [7, 8]]


Por lo que en realidad no suma las matrices, si no las listas.

Entonces, podemos convertirlas en arreglos para poder tratarles como matrices y realizar su suma.

In [12]:
A = np.array(A)
B = np.array(B)

print(A+B)

[[ 6  8]
 [10 12]]


A veces es necesario crear vectores grandes que, por ejemplo, vayan del 1 al 100 de 1 en 1. Hacer esto a mano sería muy cansado.

Con listas:

In [13]:
x = list(range(1,101))

print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


Con Numpy se puede crear esto con la función `np.arange()`. El parámetro que recibe será el inicio de la lista, el fin de la lista y el salto entre cada número.

La sintaxis es:

```python

    arreglo = np.arange(inicio_lista , fin_lista , salto_lista)

```

In [14]:
y = np.arange(1,101,1)

print(y)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


La ventaja de usar esta función es que está _optimizada_, es decir, tomará menos tiempo computacional. Además de que, ya estará en el entorno de Numpy.

Otro ejemplo, donde se definió una variable `dt` y se definió la matriz `y` que comienza en $1$, terminará en $11$ más el valor que se le dió a la variable `dt`y el salto será el valor de `dt` 

In [16]:
dt = 0.2

y = np.arange(1,11+dt,dt)

print(y)

[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11. ]


Para crear un arreglo vacío:

In [18]:
x = np.array([])

A este arreglo, así como en listas, podemos ir agregandole datos. Para esto se utiliza la función `np.append()`, los parámetros que necesita será el arreglo al que se le van a agregar datos y lo que se le va agregar.

La sintaxis es:
    
```python
    arreglo = np.append(arreglo_modificar, datos_agregar)
```

In [22]:
x = np.array([])

x = np.append(x,2)

print(x)

[2.]


La desventaja de esta función será que, creará un vector totalmente nuevo, pero que ahora tendrá el dato que se le agregó. Por ello, no es recomendable comenzar un arreglo vacío e irle agregando datos.

Lo que es viáble y más común es realizar una matriz de ceros para irle modificando sus componentes.

Para esto se utiliza la función `np.zeros()`, su parámetro será la cantidad de elementos que tendrá el arreglo.

La sintaxis es: 
    
```python

    arreglo = np.zeros(cantidad_elementos)

```

In [23]:
z = np.zeros(10)

print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


De nuevo, la ventaja será su _optimización_ en el tiempo.

Para crear una matriz de ceros, los parámetros serán la cantidad de filas y de columnas.

La sintaxis es: 
    
```python

    matriz = np.zeros((cantidad_filas , cantidad_columnas))

```

In [24]:
z = np.zeros((100,100))

print(z)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Así como se pueden crear arreglos de ceros, también se puede de unos. Para ello se utiliza la función `np.ones()`, y de igual manera su parámetro será la cantidad de elementos que se desea que tenga el arreglo.

La sintaxis es: 
    
```python

    arreglo = np.ones(cantidad_elementos)

```

In [27]:
a = np.ones(20)

print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Similar a lo anterior, se pueden crear matrices de unos.

La sintaxis es: 
    
```python

    matriz = np.ones((cantidad_filas , cantidad_columnas))

```

In [28]:
z = np.ones((2,3))

print(z)

[[1. 1. 1.]
 [1. 1. 1.]]


Como se dijo anteriormente, estos se pueden modificar de acuerdo a las necesidades como se hacía en listas.

Entonces para modificar los elementos del arreglo se manipularán por medio de $[$ $]$ las posiciones de este, como si de un vector o matriz se tratara.

En este ejemplo se creó un arreglo de ceros de nombre `s` con $7$ elementos. Después se modificó la posición $3$ del arreglo, antes siendo un $0$ y ahora un $2$. Se realizó lo mismo con la posición $5$.  

In [32]:
s = np.zeros(7)

s[3] = 2
s[5] = 9

print(s)

[0. 0. 0. 2. 0. 9. 0.]


En este ejemplo se creó un arreglo de ceros `w` y se imprimió. Luego usando un ciclo `for`se fue iterando en la cantidad de elementos del arreglo para en cada posición, asignarle su valor. Por último se imprimió después de la modificación.

In [35]:
w = np.zeros(10)

print(w)

for i in range(len(w)):
    w[i] = i
    
print(w)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


También se puede realizar en matrices.

In [36]:
D = np.zeros((5,5))

D[0][0] = 5

print(D)

[[5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


En este ejemplo, se importó una librería que otorga datos aleatorios.Luego con un `for`se fue iterando en la cantidad de elementos que contiene un arreglo `z` de ceros, entonces se le fue asignando un dato.


In [38]:
import random as ra

z = np.zeros(10)

for i in range(len(z)):
    z[i] = ra.random()
    
print(z)

[0.01433902 0.83147765 0.95528174 0.01724442 0.10771419 0.60510031
 0.08100033 0.84495594 0.28541056 0.82419213]


Una función interesante es `np.linspace()`, el cual permite crear un vector cuyos datos estarán en un intérvalo y un $n$ cantidad de datos.

La sintaxis es: 
    
```python

    vector = np.linspace(inicio_vector, fin_vector, n_cantidad)

```

El salto que se dará entre cada dato será

$$salto = \frac{fin - inicio }{n}$$

In [42]:
w = np.linspace(1,2,101)

print(w)

[1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11 1.12 1.13
 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25 1.26 1.27
 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.4  1.41
 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53 1.54 1.55
 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69
 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81 1.82 1.83
 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95 1.96 1.97
 1.98 1.99 2.  ]


Esta función es muy útil para crear gráficas.

Otro ejemplo

In [44]:
w = np.linspace(1,10,101)

print(w)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.54  1.63  1.72  1.81  1.9   1.99
  2.08  2.17  2.26  2.35  2.44  2.53  2.62  2.71  2.8   2.89  2.98  3.07
  3.16  3.25  3.34  3.43  3.52  3.61  3.7   3.79  3.88  3.97  4.06  4.15
  4.24  4.33  4.42  4.51  4.6   4.69  4.78  4.87  4.96  5.05  5.14  5.23
  5.32  5.41  5.5   5.59  5.68  5.77  5.86  5.95  6.04  6.13  6.22  6.31
  6.4   6.49  6.58  6.67  6.76  6.85  6.94  7.03  7.12  7.21  7.3   7.39
  7.48  7.57  7.66  7.75  7.84  7.93  8.02  8.11  8.2   8.29  8.38  8.47
  8.56  8.65  8.74  8.83  8.92  9.01  9.1   9.19  9.28  9.37  9.46  9.55
  9.64  9.73  9.82  9.91 10.  ]


Como se ha mencionado, Numpy permite realizar operaciones entre vectores.

Se definen dos vectores, y se realizarán operaciones entre ellos.

In [46]:
x = np.arange(1,11)

y = np.arange(11,21)

print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


- **Suma de vectores**

Se imprime la suma de los dos vectores `x` y `y`creados.

In [48]:
print(x+y)

[12 14 16 18 20 22 24 26 28 30]


- **Multiplicar por una constante**

Se imprime la multiplicación de una constante $\alpha = 3$ por el vector `x`. 

In [50]:
print(3*x)

[ 3  6  9 12 15 18 21 24 27 30]


- **Suma de una constante a los elementos** 

Se imprime la suma de una constante $\alpha = 10$ a cada elemento del vector `x`. 

In [51]:
print(x+10)

[11 12 13 14 15 16 17 18 19 20]


- **Potenciación a los elementos**

Se imprime el cuadrado de los elementos del vector `x`. 

In [52]:
print(x**2)

[  1   4   9  16  25  36  49  64  81 100]


Numpy además permite el manejo de funciones matemáticas para aplicarlo a cada componente de un vector. 

Se define un vector de datos que va de $-2\pi$ a $2\pi$, para ello se utiliza las constantes definidas en Numpy como lo es $\pi$, con el comando `np.pi`.

In [55]:
x = np.arange(-2*np.pi, 2*np.pi + np.pi,np.pi)

print(x)

[-6.28318531 -3.14159265  0.          3.14159265  6.28318531]


- **Seno**

Se aplica el seno a cada elemento del vector `x`.

In [56]:
print(np.sin(x))

[ 2.4492936e-16 -1.2246468e-16  0.0000000e+00  1.2246468e-16
 -2.4492936e-16]


- **Coseno**

Se aplica el coseno a cada elemento del vector `x`.

In [58]:
print(np.cos(x))

[ 1. -1.  1. -1.  1.]


- **Exponencial**

Se aplica el exponencial a cada elemento del vector `x`.

In [60]:
print(np.exp(x))

[1.86744273e-03 4.32139183e-02 1.00000000e+00 2.31406926e+01
 5.35491656e+02]


También se le pueden aplicar métodos.

- `nombre_arreglo.ndim`

Determina la dimensión del vector o matriz. 

In [62]:
x = np.arange(1,11)

print(x.ndim)

1


- `nombre_arreglo.size`

Determina el tamaño del vector o matriz.

In [67]:
x = np.arange(1,11)

print(x.size)

10


- `nombre_arreglo.shap`

Determina $nxm$ de una matriz.

In [66]:
D = np.zeros((5,5))

print(D.shape)

(5, 5)


***
## Álgebra Lineal

Numpy permite realizar operaciones de álgebra lineal a los vectores que se definan.

Se definen dos vectores y se realizan operaciones entre estos.

$$\begin{matrix}
\vec{x} = \begin{pmatrix}
1\\ 
2\\
3
\end{pmatrix} & \vec{y} = \begin{pmatrix}
3\\ 
4\\
5
\end{pmatrix}
\end{matrix}$$

In [71]:
x = np.array([1,2,3])
y = np.array([3,4,5])

- **Producto punto**

Se realiza el producto punto entre los dos vectores `x` y `y` con el comando `vector_1.dot(vector_2)`

$$
\vec{x}\cdot \vec{y} = (1\cdot 3 + 2\cdot 4 + 3\cdot 5) = 26
$$

In [72]:
print(x.dot(y))

26


- **Producto cruz**

Se realiza el producto cruz entre los dos vectores `x` y `y` con el comando `np.cross(vector_1,vector_2)`

$$
\vec{x}\times  \vec{y} = \begin{bmatrix}
\hat{i} & \hat{j} & \hat{k}\\ 
1 & 2 & 3\\ 
3 & 4 & 5
\end{bmatrix} = [-2,4,-2]
$$

In [73]:
print(np.cross(x,y))

[-2  4 -2]


- **Sistemas de ecuaciones**

Se resuelve un sistema de ecuaciones transformándola en una matriz y aplicando la función `np.linalg.solve(A,b)`

$$x+2y = 5$$
$$3x+4y = 6$$

$$A = \begin{bmatrix}
1 & 2\\ 
 3& 4
\end{bmatrix}
b = \begin{bmatrix}
5\\ 
6
\end{bmatrix}$$

In [77]:
A = np.array([[1,2],[3,4]])
b = np.array([5,6])

print(np.linalg.solve(A,b))

[-4.   4.5]


***
## Estadística

Así mismo, la biblioteca contiene algunas funciones para el análisis de datos estadísticos.

Se tienen los resultados de un mapeo estadístico y se realiza un análisis sobre estos.

 $$resultados = (2,3,5,7,9,1,3,4,6)$$

In [82]:
resultados = np.array([2,3,5,7,9,1,3,4,6])

- **Promedio**

Se calcula el promedio de datos obtenidos usando la función `np.mean(datos)`.

In [83]:
print(np.mean(resultados))

4.444444444444445


- **Mediana**

Se calcula la mediana de los datos obtenidos usando la función `np.median(datos)`.

In [84]:
print(np.median(resultados))

4.0


- **Percentiles**

Se calcula el percentil de los datos obtendios usando la función `np.percentile(datos,percentil)`

In [85]:
print(np.percentile(resultados,40))

3.2


- **Desviación estándar**

Se calcula la desviación estándar de los datos obtenidos usando la función `np.std(datos)`

In [86]:
print(np.std(resultados))

2.4088314876309775


Para conocer más acerca de la libreria Numpy, puedes leer la documentación oficial en la página web.

https://numpy.org